[package]
name = "project_2"
version = "0.1.0"
authors = ["Mikko Hannukainen <l5159@student.jamk.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
